spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp
    username: <USERNAME>
    password: <PASSWORD>
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger